apiVersion: v1
kind: Service
metadata:
  name: argo-server
  namespace: argo
  labels:
    app: argo-server
spec:
  clusterIP: 10.98.211.201
  clusterIPs:
  - 10.98.211.201
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    port: 2746
    protocol: TCP
    targetPort: 2746
  selector:
    app: argo-server
  sessionAffinity: None
  type: ClusterIP
