apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: corre-api-vss
  namespace: default
spec:
  # O nome do Secret do Kubernetes que será criado
  destination:
    name: corre-api-secrets
    create: true
  
  # O caminho do segredo no Vault
  path: "secret/data/corre-api"

  # O método de autenticação do Vault
  vaultAuth:
    kubernetes:
      # A role que depuramos anteriormente
      role: "debug-role"
      # A ServiceAccount que o pod usa
      serviceAccount: "corre-api-sa"
  
  # Frequência de atualização do segredo
  refreshAfter: 30m
