apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: corre-api-vss
  namespace: default
spec:
  # Referência ao recurso VaultAuth no namespace 'vault'
  vaultAuthRef: vault/default-auth

  # O caminho de montagem do motor de segredos KV-v2 no Vault
  mount: "secret"
  # O tipo do motor de segredos
  type: "kv-v2"
  
  # O caminho do segredo dentro do mount
  path: "corre-api"

  # O nome do Secret do Kubernetes que será criado
  destination:
    name: corre-api-secrets
    create: true
  
  # Frequência de atualização do segredo
  refreshAfter: 30m
