apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: default-auth
  namespace: vault
spec:
  vaultConnectionRef: default-connection
  allowedNamespaces:
  - "default"
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: "debug-role"
    serviceAccount: "corre-api-sa"