apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-app
  namespace: lab-app
  labels:
    app: lab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-app
  template:
    metadata:
      labels:
        app: lab-app
    spec:
      containers:
      - name: lab-app
        image: busybox
        command: ["sh", "-c", "while true; do echo 'Lab app running...'; sleep 3600; done"]
        envFrom:
        - secretRef:
            name: lab-app-secrets
        - secretRef:
            name: lab-app-secret
